# Generated by Django 5.2.14 on 2026-05-10 20:49

import datetime
import django.core.validators
import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use letters, spaces, or hyphens only.",
                                regex="^[A-Za-z][A-Za-z -]*$",
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use letters, spaces, or hyphens only.",
                                regex="^[A-Za-z][A-Za-z -]*$",
                            )
                        ],
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(1900, 1, 1)
                            ),
                            records.models.validate_past_date,
                        ]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("smoker", models.BooleanField(default=False)),
                (
                    "pack_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("diabetes", models.BooleanField(default=False)),
                ("insulin", models.BooleanField(default=False)),
                ("chemotherapy", models.BooleanField(default=False)),
                ("last_chemotherapy_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name", "birth_date"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateField(
                        default=datetime.date.today,
                        validators=[records.models.validate_past_date],
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT"),
                            ("MRI", "MRI"),
                            ("XR", "X-ray"),
                            ("US", "Ultrasound"),
                        ],
                        max_length=3,
                    ),
                ),
                ("reason", models.CharField(max_length=120)),
                ("diagnosis", models.CharField(max_length=120)),
                (
                    "image",
                    models.ImageField(
                        upload_to=records.models.scan_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            records.models.validate_scan_image_size,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="records.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at", "-created_at"],
            },
        ),
    ]
